

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: postgres
    password: trankimhieu123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  boot:
    message: "Hello, Employee Service"
eureka:
  instance:
    client:
      server-url:
        defaultZone: http://localhost:8761/eureka/
